apiVersion: v1
kind: Service
metadata:
  name: mcp-mssql-service
  namespace: {{ .Values.namespace }}
  labels:
    app: mcp-mssql
spec:
  selector:
    app: mcp-mssql
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    appProtocol: kgateway.dev/mcp