image:
  repository: kamalberrybytes/adk-web-ui
  tag: v5
  pullPolicy: Always

replicas: 1

ports:
  containerPort: 5000

service:
  port: 5000
  targetPort: 5000

env:
  AZURE_CLIENT_ID: "11ddc0cd-e6fc-48b6-8832-de61800fb41e"
  AZURE_TENANT_ID: "6ba231bb-ad9e-41b9-b23d-674c80196bbd"
  GATEWAY_URL: "http://agentgateway-proxy.agentgateway-system.svc.cluster.local:8080"
  AZURE_CLIENT_SECRET: ""
  REDIRECT_URI: "http://localhost:5000/auth/callback"
  BMG_API: "http://bmg-agent-service.agentgateway-system.svc.cluster.local:8070"
  SECRET_KEY: "helloworld"
  AZURE_SCOPES: "openid api://11ddc0cd-e6fc-48b6-8832-de61800fb41e/mcp.access"

namespace: agentgateway-system