image:
  repository: kamalberrybytes/mcp-hubspot
  tag: latest
  pullPolicy: Always

replicas: 1

service:
  port: 8000
  targetPort: 8000

backend:
  name: mcp-hubspot-backend
  targetName: mcp-hubspot-target
  host: mcp-hubspot-service.{{ .Values.namespace }}.svc.cluster.local
  port: 8000
  protocol: StreamableHTTP

httpRoute:
  path: /mcp/mcp-hubspot

namespace: agentgateway-system