apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-mssql-sa
  annotations:
    azure.workload.identity/client-id: "11ddc0cd-e6fc-48b6-8832-de61800fb41e"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-mssql
spec:
  selector:
    matchLabels:
      app: mcp-mssql
  template:
    metadata:
      labels:
        app: mcp-mssql
    spec:
      serviceAccountName: mcp-mssql-sa
      containers:
      - name: mcp-mssql
        image: kamalberrybytes/mssql-mcp:v1
        imagePullPolicy: Always
        env:
          - name: MSSQL_SERVER
            value: "my-mssqlserver-2022"
          - name: MSSQL_DATABASE
            value: "msdb"
          - name: MSSQL_PORT
            value: "1433"
          - name: MSSQL_USER
            value: "sa"
          - name: MSSQL_PASSWORD
            value: ""
      
---
apiVersion: v1   
kind: Service
metadata:
  name: mcp-mssql-service
  labels:
    app: mcp-mssql
spec:
  selector:
    app: mcp-mssql
  ports:
  - port: 8000
    targetPort: 8000
    appProtocol: kgateway.dev/mcp
