kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: agentgateway
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
  - protocol: {{ .Values.gateway.protocol }}
    port: {{ .Values.gateway.port }}
    name: http
    allowedRoutes:
      namespaces:
        from: All