apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-hubspot-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "11ddc0cd-e6fc-48b6-8832-de61800fb41e"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-hubspot
spec:
  selector:
    matchLabels:
      app: mcp-hubspot
  template:
    metadata:
      labels:
        app: mcp-hubspot
    spec:
      serviceAccountName: mcp-hubspot-sa
      containers:
      - name: mcp-hubspot
        image: kamalberrybytes/mcp-hubspot:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-hubspot-service
  labels:
    app: mcp-hubspot
spec:
  selector:
    app: mcp-hubspot
  ports:
  - port: 8000
    targetPort: 8000
    appProtocol: kgateway.dev/mcp

