apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.bmgUi.deployment.name }}
  labels:
    app: bmg-ui
spec:
  replicas: {{ .Values.bmgUi.deployment.replicas }}
  selector:
    matchLabels:
      app: bmg-ui
  template:
    metadata:
      labels:
        app: bmg-ui
    spec:
      containers:
        - name: bmg-ui
          image: "{{ .Values.bmgUi.deployment.image.repository }}:{{ .Values.bmgUi.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.bmgUi.deployment.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.bmgUi.deployment.port }}
          env:
            - name: AZURE_CLIENT_ID
              value: "{{ .Values.azure.clientId }}"
            - name: AZURE_TENANT_ID
              value: "{{ .Values.azure.tenantId }}"
            - name: GATEWAY_URL
              value: "{{ .Values.bmgUi.deployment.env.gatewayUrl }}"
            - name: AZURE_CLIENT_SECRET
              value: "{{ .Values.bmgUi.deployment.env.azureClientSecret }}"
            - name: REDIRECT_URI
              value: "{{ .Values.bmgUi.deployment.env.redirectUri }}"
            - name: BMG_API
              value: "{{ .Values.bmgUi.deployment.env.bmgApi }}"
            - name: SECRET_KEY
              value: "{{ .Values.bmgUi.deployment.env.secretKey }}"
            - name: AZURE_SCOPES
              value: "{{ .Values.bmgUi.deployment.env.azureScopes }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.bmgUi.service.name }}
  labels:
    app: bmg-ui
spec:
  selector:
    app: bmg-ui
  ports:
    - port: {{ .Values.bmgUi.service.port }}
      targetPort: {{ .Values.bmgUi.service.targetPort }}
      protocol: TCP
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.bmgUi.httpRoute.name }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /ui
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: {{ .Values.bmgUi.service.name }}
          port: {{ .Values.bmgUi.service.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /auth
      backendRefs:
        - name: {{ .Values.bmgUi.service.name }}
          port: {{ .Values.bmgUi.service.port }}