apiVersion: v1
kind: Service
metadata:
  name: bmg-agent-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: bmg-agent
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP