# Default values for bmg-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: sawnjordan/multi-agent
  tag: v0.8
  pullPolicy: IfNotPresent

replicas: 1

ports:
  containerPort8000: 8000
  containerPort8070: 8070

service:
  port: 8070
  targetPort: 8070

config:
  AGENT_MODE: "api"
  AGENT_PORT: "8070"
  AGENT_HOST: "0.0.0.0"
  MCP_SERVERS_JSON: '[{"url":"http://agentgateway-proxy.{{ .Values.global.namespace }}.svc.cluster.local:8080/mcp/mcp-mssql"}]'

secrets:
  DEEPSEEK_API_KEY: ""

# Global values will be merged from parent chart
global: {}