apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-example-sa
  namespace: agentgateway-system
  annotations:
    azure.workload.identity/client-id: "11ddc0cd-e6fc-48b6-8832-de61800fb41e"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-example
  namespace: agentgateway-system
spec:
  selector:
    matchLabels:
      app: mcp-example
  template:
    metadata:
      labels:
        app: mcp-example
    spec:
      serviceAccountName: mcp-example-sa
      containers:
      - name: mcp-example
        image: kamalberrybytes/mcp:1.0.0
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-example-service
  namespace: agentgateway-system
  labels:
    app: mcp-example
spec:
  selector:
    app: mcp-example
  ports:
  - port: 8000
    targetPort: 8000
    appProtocol: kgateway.dev/mcp



