apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmg-ui
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: bmg-ui
  template:
    metadata:
      labels:
        app: bmg-ui
    spec:
      containers:
      - name: bmg-ui
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.ports.containerPort }}
        env:
        - name: AZURE_CLIENT_ID
          value: {{ .Values.env.AZURE_CLIENT_ID | quote }}
        - name: AZURE_TENANT_ID
          value: {{ .Values.env.AZURE_TENANT_ID | quote }}
        - name: GATEWAY_URL
          value: {{ .Values.env.GATEWAY_URL | quote }}
        - name: AZURE_CLIENT_SECRET
          value: {{ .Values.env.AZURE_CLIENT_SECRET | quote }}
        - name: REDIRECT_URI
          value: {{ .Values.env.REDIRECT_URI | quote }}
        - name: BMG_API
          value: {{ .Values.env.BMG_API | quote }}
        - name: SECRET_KEY
          value: {{ .Values.env.SECRET_KEY | quote }}
        - name: AZURE_SCOPES
          value: {{ .Values.env.AZURE_SCOPES | quote }}