apiVersion: v1
kind: Service
metadata:
  name: bmg-ui-service
  namespace: {{ .Values.namespace }}
  labels:
    app: bmg-ui
spec:
  selector:
    app: bmg-ui
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  type: ClusterIP