apiVersion: v1
kind: ServiceAccount
metadata:
  name: adk-ui-sa
  namespace: agentgateway-system
  annotations:
    azure.workload.identity/client-id: "11ddc0cd-e6fc-48b6-8832-de61800fb41e"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adk-ui
  namespace: agentgateway-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adk-ui
  template:
    metadata:
      labels:
        app: adk-ui
    spec:
      serviceAccountName: adk-ui-sa
      containers:
      - name: adk-ui
        image: kamalberrybytes/adk-web-ui:0.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: AZURE_CLIENT_ID
          value: "11ddc0cd-e6fc-48b6-8832-de61800fb41e"
        - name: AZURE_TENANT_ID
          value: "6ba231bb-ad9e-41b9-b23d-674c80196bbd"
        - name: GATEWAY_URL
          value: "http://agentgateway-proxy.agentgateway-system.svc.cluster.local:8080"
        - name: AZURE_CLIENT_SECRET
          value: ""
        - name: REDIRECT_URI
          value: "http://localhost:5000/auth/callback"
        - name: ADK_API
          value: "http://adk-agent-service.agentgateway-system.svc.cluster.local:8070"
        - name: SECRET_KEY
          value: "helloworld"
        - name: AZURE_SCOPES
          value: "openid api://11ddc0cd-e6fc-48b6-8832-de61800fb41e/mcp.access"
---
apiVersion: v1
kind: Service
metadata:
  name: adk-ui-service
  namespace: agentgateway-system
  labels:
    app: adk-ui
spec:
  #type: NodePort
  selector:
    app: adk-ui
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
        #   nodePort: 30441
