apiVersion: apps/v1
kind: Deployment
metadata:
  name: adk-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adk-ui
  template:
    metadata:
      labels:
        app: adk-ui
    spec:
      serviceAccountName: adk-ui-sa
      containers:
      - name: adk-ui
        image: kamalberrybytes/adk-web-ui:v4
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: AZURE_CLIENT_ID
          value: "0f998a91-b26e-4fa7-bf19-7d9b2c487cdd"
        - name: AZURE_TENANT_ID
          value: "a842fba6-0f79-40e7-98f3-21cb1a8c3365"
        - name: GATEWAY_URL
          value: "http://agentgateway-proxy.agentgateway-system.svc.cluster.local:8080"
        - name: AZURE_CLIENT_SECRET
          value: ""
        - name: REDIRECT_URI
          value: "http://localhost:5000/auth/callback"
        - name: ADK_API
          value: "http://adk-agent-service.agentgateway-system.svc.cluster.local:8070"
        - name: SECRET_KEY
          value: "helloworld"
        - name: AZURE_SCOPES
          value: "openid api://0f998a91-b26e-4fa7-bf19-7d9b2c487cdd/mcp.access"
---
apiVersion: v1
kind: Service
metadata:
  name: adk-ui-service
  labels:
    app: adk-ui
spec:
  selector:
    app: adk-ui
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP

