apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mcp-mssql
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
  - name: agentgateway-proxy
  rules:
   - matches:
       - path:
           type: PathPrefix
           value: {{ .Values.httpRoute.path }}
     backendRefs:
       - name: {{ .Values.backend.name }}
         group: agentgateway.dev
         kind: AgentgatewayBackend