apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmg-agent-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: bmg-agent
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: bmg-agent
  template:
    metadata:
      labels:
        app: bmg-agent
    spec:
      containers:
        - name: bmg-agent
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ports.containerPort8000 }}
            - containerPort: {{ .Values.ports.containerPort8070 }}
          envFrom:
          - configMapRef:
              name: bmg-agent-config
          - secretRef:
              name: bmg-agent-secrets
      restartPolicy: Always